name: Quark
keywords: jekyll, theme, framework, 
url: /
markdown: kramdown
permalink: pretty
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
author: Enoch Appathurai (@enociz)
owner: Enoch Appathurai (@enociz)
font-location: https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700
global-css-location: <!--nothing here-->
site-logo-location: /img/logo.png
collections:
- nav-items
