name: Quark
description: A collection of the most common components in the Web industry, as a simple to use Jekyll framework.
url: /
markdown: kramdown
permalink: pretty
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

collections:
- nav-items
